# This is a basic workflow to help you get started with Actions

name: Issue-Responder

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  respond:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Add response comment
        uses: froi-poc-and-demos/github-ce-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
